export const data = [
  {
    name: "Tom",
    avatar: "images/boy1.jpg",
    age: 25,
    bio: "Art. Literature. Natural wine. Yoga.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Tim",
    avatar: "images/dog-bella.jpg",
    age: 43,
    bio: "Dogs. Walking. Swimming.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Jane",
    avatar: "images/girl1.jpg",
    age: 30,
    bio: "How are you?",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "John",
    avatar: "images/boy2.jpg",
    age: 31,
    bio: "IT, Movies",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "David",
    avatar: "images/boy3.jpg",
    age: 18,
    bio: "Walking in nature. Running.",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Simon",
    avatar: "images/boy4.jpg",
    age: 29,
    bio: "Wine & Dine",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Isabella",
    avatar: "images/girl2.jpg",
    age: 35,
    bio: "Painting and Photography",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
  {
    name: "Ann",
    avatar: "images/girl3.jpg",
    age: 30,
    bio: "Pilates",
    hasBeenSwiped: false,
    hasBeenLiked: false,
  },
];
